name: pull_request_check

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v46

      - name: Check changed files
        run: |
          if [ ${{ steps.changed_files.outputs.all_changed_files_count }} -ne 1 ]; then
            echo "your changed files count must be 1"
            exit 1
          fi
          for file in ${{ steps.changed_files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install

      - run: bun run check

      - run: bun run format

      - run: bun run lint

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Commit updated files if any
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, committing..."
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "chore: update bun.lock / format code [skip ci]"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit"
          fi
